---
title: Project Review Template 
author: Xueyan Hu
date: 04-24-2024
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Geographic Spread of Seasonal Flu

Name of project author(s): Clarke Miller 

Name of project reviewer: Xueyan Hu


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/knits into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

Generally the introduction part is described well for flu and virus in 2 paragraphs, but I think it could be better if geographic spread related contents since the title is about this.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* some contextualization and motivation



## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

I think the questions are listed clearly to me, but I think there is a gap between introduction and raised questions that might needs further explanation.

### Summary assessment

* question/hypotheses somewhat explained



## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

Source is provided and overall described well and meta-information is included also. 

### Summary assessment

* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

The whole cleaning process is clear and well organized. The figures generated look nice and the explanation is in detailed, so I can understand them easily.
But I think 'Figure 3: World Flu Burden by Region' could be improved a little bit because there are too many observations in the bar chart, it is not easy to differentiate them. All of the figures are shown in the main manuscript, and the summary table is impressive. 

### Summary assessment

* some weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

I think the linear regression models chosen are appropriate and there is no problem during data analysis. But the author might want to delete some words "3.5 Statistical Analysis:" in your manuscript which wasn't used by the author. 

### Summary assessment

* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The results are explained in detail and can be clearly understood. Tables and figures are presented as assisting tools. But I think it will be better if random forest model could be introduced a little bit more deeper and the figures of rf model could be improved since they only show the error changes by the number of tree, it could be better if prediction related information shown at the same time.

### Summary assessment

* results are presented ok, with room for improvement



## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The discussion part include the finding obtained from data analysis with possible reasons of the results are also listed and analysed. I just have one small question. Since random forest model is not suitable for this data, then does the author need to suggest another better model or compared the result of random forest model with simple linear model? Strengths and limitations are acknowledged.

### Summary assessment

* strong, complete and clear discussion


## Further comments

_I am not so sure besides random forest model, there won't be any more machine learning models could be fit to the data. So I may suggest trying other machine learning models or just using simple linear regression for prediction and compare the performance between 2 model._



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

I think I can find most of the files but it will be better if they are labeled more clearly so it will let me target the file I'm looking for right away among piled files. And there are some unused files or folders haven't been removed from the project folder.

### Summary assessment

* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

I think most of the steps are quite clear, but it will be better if unecessary words in the template could be deleted by the author.

### Summary assessment

* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

Almost all the results are fully reproducible besides the following part. I have no idea why it needs java to be downloaded. But it doesn't affect other codes if I skip this line so it is not a problem. The instruction is provided is mainly in manuscript, but I think it could be better for me to understand if it can be explained a little more.

suppressPackageStartupMessages(library(xlsx))
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

Warning: running command '/usr/libexec/java_home' had status 1Warning: Cannot find JVM library 'NA/lib/server/libjvm.dylib'
Install Java and/or check JAVA_HOME (if in doubt, do NOT set it, it will be detected)Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JVM could not be found

### Summary assessment
 
* small parts not reproducible or required manual intervention 



## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Questions are fully and thoroughly addressed. The overall study looks thorough, too. And 2 model types are involved in the full data analysis. But I still hold the thought that maybe more ml models could be applied and compared.

### Summary assessment

* strong level of thorougness


## Further comments

_I think the way how the author organize the files and folders is a little bit off to me , and it could be improved a little bit. Besides, it will be better if all of the needed packages could be listed at the top of the quarto files. Also, there are some repeated and old contents in the quarto files which can be removed or it could be a little bit confusing to me. Read.me files should be updated, too. _





